### ISSUE TITLE
reverseDataRecursive results in an infinite loop

### ISSUE THREAD

**Issue by Vulfpeck** [initiator26/Lafore5_LinkedLists#2]
Cause: unknown
Steps to replicate: call the function

Sample input 10, 11, 12 …..  , 20

output 20, 19, 18, …. 10, 11, 10, 11,10

**Comment by Zireael26** [comment]
Can not reproduce
You most like used the makeLoop() function and then called display() without breaking the loopwith findAndRemoveLoop()
